version: "3.9"
services:
    web:
        build:
            args:
                ConnectionString: "${DatabaseConnectionString};" 
                ServiceWeltUser: "${ServiceWeltUser}"
                ServiceWeltPassword: "${ServiceWeltPassword}"
                ServiceWeltUrl: "${ServiceWeltUrl}"       
            context: .      
        ports:
            - "80:6003"
            - "443:6004"
        volumes:
            - ./web/root/.aspnet/DataProtection-Keys:/root/.aspnet/DataProtection-Keys:rw
        environment:
            DOTNET_CLI_TELEMETRY_OPTOUT: 1
        depends_on:
            - db            
    db:
        image: "mcr.microsoft.com/azure-sql-edge:latest"
        container_name: "mssql"
        restart: always        
        ports:
            - 1433:1433        
        volumes:
            - ./data/mssql/data/:/var/opt/mssql/data
            - ./data/mssql/log/:/var/opt/mssql/log
            - ./data/mssql/secrets/:/var/opt/mssql/secrets
        environment:
            MSSQL_SA_PASSWORD: ${DatabasePassword}
            ACCEPT_EULA: Y
