version: "3.9"
services:
    web:
        build:
            args:
                ConnectionString: "${DatabaseConnectionString};"
                ServiceWeltUser: "${ServiceWeltUser}"
                ServiceWeltPassword: "${ServiceWeltPassword}"
                ServiceWeltUrl: "${ServiceWeltUrl}"
            context: .
            dockerfile: Dockerfile_DbMigrate    
        ports:
            - "80:6003"
            - "443:6004"
        volumes:
            - ./web/root/.aspnet/DataProtection-Keys:/root/.aspnet/DataProtection-Keys:rw    
            - ./Data/Migrations:/app/Data/Migrations:rw          
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/azure-sql-edge:latest"
        user: root        
        container_name: "mssql"
        restart: always        
        ports:
            - "1433:1433" 
            - "1434:1434" 
            - "1431:1431"                 
        volumes:
            - ./data/mssql/data/:/var/opt/mssql/data
            - ./data/mssql/log/:/var/opt/mssql/log
            - ./data/mssql/secrets/:/var/opt/mssql/secrets
        environment:
            MSSQL_SA_PASSWORD: ${DatabasePassword}
            ACCEPT_EULA: Y
